# Generated by Django 3.0.4 on 2020-03-30 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=70, verbose_name='название статьи')),
                ('article_text', models.TextField(verbose_name='текст статьи')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('homepage', models.BooleanField(verbose_name='Разместить на главной')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20, verbose_name='VIN код')),
                ('brend_car', models.CharField(max_length=20, verbose_name='марка')),
                ('model_car', models.CharField(max_length=20, verbose_name='модель')),
                ('year', models.IntegerField(verbose_name='год выпуска')),
                ('motor', models.CharField(max_length=10, verbose_name='двигатель')),
                ('transmission', models.CharField(choices=[('механика', 'механика'), ('автомат', 'автомат'), ('easytronic', 'easytronic')], default='механика', max_length=10, verbose_name='КПП')),
                ('number', models.CharField(max_length=10, verbose_name='госномер')),
                ('photo', models.ImageField(default='cars/nophotocars.jpg', upload_to='cars/', verbose_name='фото')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50, verbose_name='вид работы')),
                ('description', models.TextField(blank=True, verbose_name='описание работы')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mileage', models.IntegerField(blank=True, verbose_name='пробег')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('description', models.TextField(verbose_name='Описание работ и проблем')),
                ('repair_cost', models.IntegerField(default=0, verbose_name='Стоимость ремонта BYN')),
                ('photo01', models.ImageField(default='repairs/nophoto.png', upload_to='repairs/', verbose_name='фото01')),
                ('photo02', models.ImageField(default='repairs/nophoto.png', upload_to='repairs/', verbose_name='фото02')),
                ('photo03', models.ImageField(default='repairs/nophoto.png', upload_to='repairs/', verbose_name='фото03')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sto.Car')),
                ('repworks', models.ManyToManyField(related_name='works', to='sto.Work')),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Ремонты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('phone_number', models.CharField(max_length=15, verbose_name='телефон')),
                ('photo', models.ImageField(default='clients/def.jpg', upload_to='clients/', verbose_name='фото')),
                ('status', models.CharField(choices=[('новый', 'без скидок'), ('скидка', 'скидка')], default='без скидок', max_length=20, verbose_name='статус')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('cars', models.ManyToManyField(blank=True, related_name='cars', to='sto.Car')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
