# Generated by Django 3.0.4 on 2020-03-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
