# Generated by Django 3.0.4 on 2020-03-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20, verbose_name='VIN код')),
                ('brend_car', models.CharField(max_length=20, verbose_name='марка')),
                ('model_car', models.CharField(max_length=20, verbose_name='модель')),
                ('year', models.IntegerField(verbose_name='год выпуска')),
                ('motor', models.CharField(max_length=10, verbose_name='двигатель')),
                ('transmission', models.CharField(choices=[('механика', 'механика'), ('автомат', 'автомат')], default='механика', max_length=10, verbose_name='КПП')),
                ('number', models.CharField(max_length=10, verbose_name='госномер')),
                ('photo', models.ImageField(default='nophotocars.jpg', upload_to='cars/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
