# Generated by Django 3.0.4 on 2020-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(default='clients/def.jpg', upload_to='clients/', verbose_name='фото')),
                ('status', models.CharField(choices=[('без скидок', 'без скидок'), ('скидка', 'скидка')], default='start', max_length=20)),
                ('description', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('cars', models.ManyToManyField(related_name='cars', to='sto.Car')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
