# Generated by Django 3.0.4 on 2020-03-29 06:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0010_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=tinymce.models.HTMLField(verbose_name='текст статьи'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='нет описания', max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='cars/nophotocars.jpg', upload_to='cars/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('механика', 'механика'), ('автомат', 'автомат'), ('easytronic', 'easytronic')], default='механика', max_length=10, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='cars', to='sto.Car'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('без скидок', 'без скидок'), ('скидка', 'скидка')], default='без скидок', max_length=20),
        ),
        migrations.AlterField(
            model_name='repair',
            name='photo01',
            field=models.ImageField(default='repairs/nophoto.png', upload_to='repairs/', verbose_name='фото01'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='photo02',
            field=models.ImageField(default='repairs/nophoto.png', upload_to='repairs/', verbose_name='фото02'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='photo03',
            field=models.ImageField(default='repairs/nophoto.png', upload_to='repairs/', verbose_name='фото03'),
        ),
    ]
